# This workflow builds a Docker image and pushes it to Docker Hub on push to main or devops and then deploys the docker image on EC2 Instance via ssh
name: Build and Push Docker Image

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/majorproject:latest

      - name: Image digest
        run: echo "Image digest is ${{ steps.docker_build.outputs.digest }}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull deapool678/majorproject:latest
            docker stop majorproject || true
            docker rm majorproject || true
            docker run -d --name majorproject -p 80:8080 --env-file /home/ubuntu/.env deapool678/majorproject:latest
